[package]
name = "jsonschema-luau"
version = "1.1.0"
edition = "2024"
authors = ["Amir Farzamnia <amirfarzamnia@proton.me>"]
license = "MIT"
description = "Convert JSON Schemas to Luau type definitions with full support for constraints and advanced schema features."
readme = "README.md"
homepage = "https://github.com/streamier-labs/jsonschema-luau#readme"
repository = "https://github.com/streamier-labs/jsonschema-luau"
categories = ["development-tools", "parser-implementations"]
keywords = ["schema", "jsonschema", "luau", "type-generation", "codegen"]

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.19"
clap = { version = "4.6.4", features = ["derive"] }
convert_case = "0.11.0"

[[bin]]
name = "jsonschema-luau"
path = "src/main.rs"

[lib]
name = "json_schema_to_luau"
path = "src/lib.rs"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
